### ISSUE TITLE
No private key file generated after wallet backup

### ISSUE THREAD

**Issue by sinoda168** [ubiq/fusion#10]
I synced the wallet and get into it. Then I went to main menu, clicked Acounts --> Backup -->Account. I guess it would generate a private key file in keystore forlder. But nothing in there.

1. How can I backup my ubiq wallet? 

2. Only one wallet is risky. Does ubiq has other wallet option like light wallet?

Thank you very much for answering.

**Comment by jyap808** [comment]
yes you can load up the keystore in pyrus.ubiqsmart.com and it will show the private key.

**Comment by jyap808** [comment]
In Fusion if you go Accounts > Backup it will open the keystore folder. Backup your keystore files (file names start with UTC).

**Comment by sinoda168** [comment]
Thank you. I'm starting figuring it out.
