### ISSUE TITLE
Wallet is no sending some Transactions  

### ISSUE THREAD

**Issue by Jorgerhb** [ubiq/fusion#11]
#### System information
``````
Version: `0.8.10`
OS & Version: WIN 10 64 PRO
Node type: `eth/geth(default)`
``````
Hello 

I having trouble with the Fusion wallet and cant find a solutions anywhere. 

I Sent 3 trasactions to my exchange.. 

The last transactions took minutes to show up on the exchange 

The 2 first transactions are over 24 hours and nothing, not a single confirmations.. 

![trans1](https://user-images.githubusercontent.com/30127461/28174120-2d77e82a-67b6-11e7-8cdd-8a7d14a7bb83.png)
![wallet](https://user-images.githubusercontent.com/30127461/28174119-2d76dc82-67b6-11e7-8797-24fe8d950f43.png)
![trans2](https://user-images.githubusercontent.com/30127461/28174187-60691f42-67b6-11e7-8b22-155b140a6905.png)

Nothing on the Explorer 

[node.zip](https://github.com/ubiq/fusion/files/1145728/node.zip)

Please advise what is going on... 

Thanks 
 
- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by ob7** [comment]
If the transactions did not get picked up in such a long time, then they will remain in the wallet that tried to send them.  Simply resend them with a higher mining fee to ensure your transaction is included in the next block.
