### ISSUE TITLE
Fusion Ubiq Wallet Address not showing tokens

### ISSUE THREAD

**Issue by myriadcorp** [ubiq/fusion#13]
#### System information
``````
Version: `8.1`
OS & Version: windows
Node type: `eth/geth(default)` Fusion Wallet for Ubiq

I did a test mine to the Fusion Ubiq wallet address the Windows desktop wallet gave me.  The pool deposited 9 tokens to the address but they are not showing up in my Fusion desktop Ubiq wallet.  When I type in the Ubiq address on https://pyrus.ubiqsmart.com it shows the 9 tokens.  However, I cannot move these tokens or get them to work with my desktop wallet.  Can you please advise on how to get the desktop wallet to see the tokens deposited to the address it gave me?  


Thank you.
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by jyap808** [comment]
You need to manually add the token in Fusion.

Which token?

**Comment by myriadcorp** [comment]
How do you manually add the tokens in Fusion? Fusion gave me my ubiq wallet address the pool is sending tokens to.  Why wouldn't they show up in the wallet once the pool sends them?  The wallet address in fusion is at 0.00.

**Comment by jyap808** [comment]
come chat in Slack. slack.ubiqsmart.com
