### ISSUE TITLE
Fusion stuck in browser and cant get to actual wallet

### ISSUE THREAD

**Issue by marleyrox** [ubiq/fusion#15]
#### System information
``````
Version: `0.8.9
Windows 10 64 bit
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by marleyrox** [comment]
My wallet is stuck and went nuts.  I had about 46 UBIQ inside and I was doing a backup and nothing happened.  Then started blinking and my machine rebooted.  Since I dont think i got a good backup.  Is everything gone now?

**Comment by marleyrox** [comment]
[Fusion.zip](https://github.com/ubiq/fusion/files/1192553/Fusion.zip)
Here are the log files I tried a reinstall and that did nothing.  I hope that wasnt a bad move

**Comment by vinrathod** [comment]
Having the same issue since today. Installed it on mac two days ago. Now stuck. It just opens up the browser and my wallet is nowhere seen

**Comment by marleyrox** [comment]
Whatever you do, dont re-install the software even if its a different directory.  Thats what I did.  The keyfile you created is your users directory on the C drive.  If you reinstall, the keyfile is toast.  Find your original keyfile and then you can may be able to use that to get your coin back.  In my case, my original was overwritten so my Ubiq went bye bye.  Your only other bet is is you have a backup of your system at a point in time and restore it.  Ill never use this wallet again.  Ill just use the Pyrus wallet instead.  Lesson learned.  This wallet is not ready for prime time in my opinion,  And for the record, I got no response from Fusion support so take it for what its worth.  Not much help to be expected.

**Comment by vinrathod** [comment]
Thx to ur advice I did not reinstall. Have copied and backed up the wallet hoping someday i'll get my coins back. I am not keeping my hopes to high on ever recovering the coins tho. It is for sure Fusion wallet is not cutout well. Pyrus is the only option left now.:(

**Comment by forrishizzle** [comment]
I was stuck for a while.. the solution is to drag and drop your keystore file into the fusion app which will take you to the wallet again. 

find it in c:\users\(username)\appdata\roaming\ubiq\keystore

very weird!!!!!! need to fix this asap.

**Comment by iquidus** [comment]
you can reset the ui by entering https://wallet.ubiqsmart.io/?reset-tabs=true in the url bar.

Also, it is good practice to back up your wallets before sending coins to them.
