### ISSUE TITLE
Fusion wallet loosing some deposit transactions

### ISSUE THREAD

**Issue by g4it** [ubiq/fusion#17]
I have regular deposit transaction from ubiqpool mining to my fusion wallet.

I noticed that the last 2 months at least 2 transactions have not appeared in my Fusion wallet.

I have checked ubiqscan.io and eveything seems OK, just the UBIQs never appear in my wallet.

One specific txn is 0xabd1c2522de0f90e5924d020a5b2dc21c32b537290740f799e0fbbb2e510c23a

**Comment by 008** [comment]
18 days ago
