### ISSUE TITLE
password wrong again and again...?

### ISSUE THREAD

**Issue by ukhalid100** [ubiq/fusion#18]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by ukhalid100** [comment]
[node.log.zip](https://github.com/ubiq/fusion/files/1289623/node.log.zip)
![untitled](https://user-images.githubusercontent.com/31496583/30238316-5b0383e8-954d-11e7-84fd-7d7a484039d0.png)

**Comment by iquidus** [comment]
Forgetting/mistyping password is not a fusion related issue. Closing.
