### ISSUE TITLE
Reloading from the Right-Pane Using Right-Click Menu Causes a "404 Not Found" Error

### ISSUE THREAD

**Issue by outragedhuman** [ubiq/fusion#2]
#### System information
``````
Version: 0.8.9
OS & Version: windows
Node type: `gubiq/fusion`
``````

#### STR:

1. Launch Fusion
2. Create an account using accounts -> new account
3. Select the account from the left pane
4. On the right pane, right click
5. Choose "reload"

Expected: Pane refreshes and shows new data (if any)
Actual: Error: 404 not found (see below)

![image](https://cloud.githubusercontent.com/assets/6742283/24177903/d69c8e5e-0e7b-11e7-94e4-eabbec0266b1.png)

Workaround: Use the back arrow located near the upper-left:

![image](https://cloud.githubusercontent.com/assets/6742283/24177970/6287e5bc-0e7c-11e7-857c-12c912502f73.png)

**Comment by iquidus** [comment]
potentially an nginx reverse proxy issue on the dapp wallet server, shall investigate further.

note: reloading on the main 'wallets' view, works as expected.

**Comment by jyap808** [comment]
Stale issue. Not an issue.
