### ISSUE TITLE
Fusion won`t sync

### ISSUE THREAD

**Issue by sirKainPL** [ubiq/fusion#21]
Fusion worked fine but for a while it wont sync even when peers are available.

Windows clock is set for auto sync, firewall disable ...
Any advice?
[FusionLOG.zip](https://github.com/ubiq/fusion/files/1293730/FusionLOG.zip)

I`m already 20 days behind :(

#### System information
``````
Version: `0.8.10`
OS & Version: windows 10 x64
Node type: `eth/geth(default)`
``````

**Comment by particularly** [comment]
I'm having the exact same problem. Anyone help?

**Comment by iquidus** [comment]
Update to latest version of fusion (0.9.2)

**Comment by ob7** [comment]
If peers are available, then the wallet should sync.  I only think maybe a firewall is stopping other nodes from wanting to send you data.  But its never been an issue for me on linux or windows as far as firewall goes.  One way to jump start your syncing process to add an updated list of connections in the root folder of ubiq.
