### ISSUE TITLE
Why is the recent transfer so slow? The Synchronization is also slow. The Almost fixed The The Can someone explain it? 

### ISSUE THREAD

**Issue by WLIG** [ubiq/fusion#23]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by iquidus** [comment]
There are many factors involved. Syncing speed depends on connected peers, your internet connection, # of transactions in blocks, your hardware (validating blocks). Transaction times vary depending on current blocktimes, altho they average out to target time (88seconds) some blocks are slower/faster than others.
