### ISSUE TITLE
Question regarding Fusion I switched between the main network and the test network and lost my bitcoins is there a way of retrieving them ? 

### ISSUE THREAD

**Issue by madpc44** [ubiq/fusion#26]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by madpc44** [comment]
Fusion V0.9.2
OS windows 10
Gubiq 1.5.12
2 payments 1 lost and 1 never arrived

**Comment by iquidus** [comment]
Swap back to the main network.

**Comment by madpc44** [comment]
Did that straight away my original coins are missing and the ones waiting to be paid have not come down either.

 

--

Paul Gordon MBCS

paul@madpc.co.uk

**Comment by theis0** [comment]
mine is stuck on the testnet or (private). does not switch back even when choosing mainnet. I might have lost all my UBQ coins. Any reason you did not separate the developer version from the mainstream users version?

**Comment by iquidus** [comment]
Your coins are not lost. If unable to get fusion back on mainnet you can load your wallet file in pyrus and use from there.
