### ISSUE TITLE
I send by mistake to my ethereum address how to cancel?

### ISSUE THREAD

**Issue by kostasmoure** [ubiq/fusion#27]
Hi to all,

i send by mistake some ubiq coins to my ethereum address. How to cancel and make the transaction again?

Thank you in advance

**Comment by iquidus** [comment]
You cant cancel if the transaction has already been included a block.

However, addresses are compatible, you can import your ethereum address and your ubiq will be there.
If using myetherwallet for ethereum, just change the network to UBQ in the top right network dropdown.

Or import your ethereum wallet file (.json) into fusion. You will still need to use the correct passphrase to send from it (the one you set when creating the ethereum address)

**Comment by kostasmoure** [comment]
the wallet for ethereum is bittrex and it was generated automatic by bittrex and i havent go any passphrase. Maybe its better to contact with bittrex?

Ubiqcoin from fusion (wallet address)
Ethereum from bittrex (wallet address)  

both are mine

**Comment by iquidus** [comment]
ah yeah, if you sent to an ethereum wallet controlled by a service, you'll need to submit a support ticket with them.

**Comment by kostasmoure** [comment]
Thank you iquidus. I have already send them a message.
