### ISSUE TITLE
Missing send transaction in my Fusion (0.9.2) account wallet 

### ISSUE THREAD

**Issue by pigseye** [ubiq/fusion#29]
Fusion 0.9.2
Windows 10

Sent a small amount of Ubiq to my Ledger nano.  Transaction is displayed and I can watch the confirmations.

Then sent a larger amount of Ubiq to the Ledger nano and no transaction is displayed so I can't watch the confirmation process.  A few minutes later the Ubiq shows up on my Ledger which is good.

If I look on Etherbase it shows the send transaction but it is not displayed in my account wallet.

How can I get my fusion account wallet to display all transactions executed?

**Comment by iquidus** [comment]
You can see transactions on a block explorer such as ubiqscan.io, search for your address.

**Comment by ob7** [comment]
If you mean to say: "How do I see all transactions rather than only recent ones" then I don't know the answer.  I think the wallet is coded to only show recent and needs to have the feature of seeing all transactions added.
