### ISSUE TITLE
Why does Windows installer show "Press Win + G to take a screenshot"?

### ISSUE THREAD

**Issue by realuser** [ubiq/fusion#31]
When installing Fusion 0.9.2 on Window 10 there are two messages that pop up.  One says "Press Win + G to take a screenshot" and the other says "Press Win + G to open Game bar".  I vaguely remember seeing those once before a long time ago in another context.  Why do they show up on the Fusion install?

![ubiq-gamebar](https://user-images.githubusercontent.com/7472570/34438011-441d8702-ec58-11e7-872d-ed188caeda0d.jpg)

![ubiq-screenshot](https://user-images.githubusercontent.com/7472570/34438013-49c179ca-ec58-11e7-8552-bbcf9d77ace5.jpg)

```
Version: `0.9.2`
OS & Version: Windows 10 Pro 64-bit
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by iquidus** [comment]
This is due to fusion using electron, windows 10 detects it as a game. You can disable this behavior in your windows settings, or simply ignore it.
