### ISSUE TITLE
fusion not starting 

### ISSUE THREAD

**Issue by badi81** [ubiq/fusion#32]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by iquidus** [comment]
Please provide more information.

**Comment by jyap808** [comment]
Stale issue. Not an issue.
