### ISSUE TITLE
Incoming transactions to wallet contract are not showing up properly

### ISSUE THREAD

**Issue by CreamyG31337** [ubiq/fusion#35]
- [x ] I've asked for help in the [Ubiq  Discord](https://discord.gg/HF6vEGF) before filing this issue.
```
Version: `0.9.2`
OS & Version: Windows 10
Node version: `gubiq 1.5.12`
Number of blocks synchronized: 346725
```
The values of the transactions are correctly added to my balance, and it appears that the fees are paid and they were sent to me correctly, but the wallet is showing several transactions as unconfirmed and claiming 0 fees / gas

![image](https://user-images.githubusercontent.com/11222932/34861374-a0a16894-f721-11e7-9596-efe1cf9e0886.png)
https://ubiqexplorer.com/transaction/0x3bf959dd9483e7908a0ddd963f1ebd55a1d11ce426200dcfe69baf23169ad777

![image](https://user-images.githubusercontent.com/11222932/34861398-c008062a-f721-11e7-8f60-a52b3ebd8fb0.png)
https://ubiqexplorer.com/transaction/0x843479d84bb0fb0ae3d5dda1433be10d6fc8981f98a9f7f64b7a269948b19af4

![image](https://user-images.githubusercontent.com/11222932/34861412-d574717e-f721-11e7-827a-1f692d8f340e.png)
https://ubiqexplorer.com/transaction/0x73f2d1a56f2a4f9db53b460e0bcc0b3ddd1a3c01851b22eaf0e9fda2a53e4651

https://ubiqscan.io/address/0x6b8c2668dbb1e0315034f26ed4b477d8d2cd5fac

No amount of restarting Fusion corrects this. I tried to backup and restore the account + wallet but gave up for now on that too.

**Comment by CreamyG31337** [comment]
After restoring this wallet contract to another instance of Fusion, the transactions are all showing up fine there. So the transactions themselves are fine, it's just some issue with Fusion. Are there any cache files I can delete, and how do I force it to re-sync everything from scratch? Or are there some other suggestions I can try?

**Comment by jyap808** [comment]
Stale issue. Not an issue.
