### ISSUE TITLE
Discord sees Fusion running and thinks it is 'Kega Fusion'

### ISSUE THREAD

**Issue by icarusglider** [ubiq/fusion#37]
Somehow the Discord chat client sees the Fusion client running and labels the user as playing 'Kega Fusion'. This could be a security vulnerability as a targeted DoS attack on Ubiq nodes could allow someone to monitor status of Discord users and reveal their IP if/when the Fusion application crashes.

**Comment by iquidus** [comment]
Users can turn this off in their discord settings, or customize it to say something else. User Settings -> Games -> Display currently running game as a status message. 

I'm not sure what else can be done about this, however you raise an interesting scenario.
