### ISSUE TITLE
Account Disappeared

### ISSUE THREAD

**Issue by sparklingSun** [ubiq/fusion#38]
- [ ] I've asked for help in the [Ubiq  Discord](https://discord.gg/HF6vEGF) before filing this issue.
I have searched for this issue everywhere and haven't found an answer.  I had been using Fusion for months mining ubiq.  Monday I ran Fusion, it did all the syncing and updates.  Next, it showed the current balance then changed  the balance to 0,   I tried running fusion again and the account disappeared.  I could not find the UTC file anywhere.  Not in the recycle bin either.   I'm running Windows 10.   Have I lost my account since I can't find the UTC or a backup anywhere? Fusion version 0.8.10

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `gubiq 0.0.0`
Number of blocks synchronized: 0
```

**Comment by jyap808** [comment]
Stale issue. Not an issue.
