### ISSUE TITLE
Cannot get Accounts page to appear on Test or Main

### ISSUE THREAD

**Issue by agnewpickens** [ubiq/fusion#4]
IBM Thinkcentre 8GB RAM

Version: 0.8.9 Wallet, Geth 1.5.11
OS & Version: Windows 7 Pro
Node type:  Geth

I am unable to return to my Ubiq Wallet on both Test and Mainnet
and have been unable to send funds from Bittrex to my Ubiq wallet
for over a week.

![ubiq](https://cloud.githubusercontent.com/assets/18013756/25593964/da61c23a-2e8c-11e7-92fa-a401bd1b8cee.PNG)

**Comment by outragedhuman** [comment]
@agnewpickens Could you attach a screenshot of your wallet when it's on the mainnet?

You can get there by going to Develop > Network > and then select "Main Network"

**Comment by krislester123** [comment]
Hi, I have the same issue and cannot get any accounts. This seemed to happen when I tried to import a wallet and nothing I have done has been able to get this back so far (including a full reinstall).

![capture](https://user-images.githubusercontent.com/29441296/27153289-31aa5822-5151-11e7-997b-187cdaca72ba.JPG)

**Comment by krislester123** [comment]
I've just managed to get it back through messing around in the GUI. I typed in the web address within the browser to go to the Ubiq website and the browse button reappeared, I clicked back on this and my wallet re-appeared.

**Comment by outragedhuman** [comment]
Glad you got it straightened out. Sorry I didn't see your update from the 1st, didn't get an email on that one for some reason.

**Comment by iquidus** [comment]
If anyone else encounters this, in the url bar enter https://wallet.ubiqsmart.io?reset-tabs=true
