### ISSUE TITLE
Fusion was working and then it said it couldn't connect to node

### ISSUE THREAD

**Issue by KrypticAngel** [ubiq/fusion#42]
I just downloaded the newest version of Fusion for UBIQ and it was working at first and then I closed it and when I tried to reopen it, it said that it couldn't connect to node.

**Comment by rtalintyre** [comment]
I also had a similar issue where fusion would start and attempt to connect to peers but would never find any to connect and so it would stay stuck at the block height it got to when it last successfully opened. The only way I found around this was to delete all files in the AppData\Roaming\Ubiq\gubiq directory. I am running Windows 10 with all latest updates installed.

**Comment by Kelan-Mining** [comment]
I am also having the same issues with Fusion.. I also tried the delete idea above but still nothing.. just wont sync.. cant find peers and yet I can look around the blockchain and see my funds, Need help with getting this program to run. 
It was working then it just stopped. I have now installed it on another PC and dropped the backup file into the install as stated I have the wallet address but still no sync.. 
I am running windows 7 on both rigs.
Checked all firewalls and network gateway.
All set correctly.
Can someone please help.

**Comment by jyap808** [comment]
Stale issue. Not an issue.

**Comment by fateh206** [comment]
https://cryptotabbrowser.com/4527137
