### ISSUE TITLE
Escher

### ISSUE THREAD

**Issue by kryptomuz** [ubiq/fusion#43]
- [ ] I've asked for help in the [Ubiq  Discord](https://discord.gg/HF6vEGF) before filing this issue.

```
Version: `0.8.10`
OS & Version: windows 10
Node version: `gubiq 1.5.12`
Number of blocks synchronized: 478,656
```

Hi,
I was make a contract for escher airdrop 1 and i didn't get any escher.
I can see just my ubiq.

**Comment by jyap808** [comment]
Stale issue. Not an issue.
