### ISSUE TITLE
Mining Hashrate Notification in Windows Gui

### ISSUE THREAD

**Issue by kwaichangdave** [ubiq/fusion#44]
When I solo mined with 0.9.2, a small mining icon appeared on the lower left with the hashrate accurately reported. Now in 0.10.0 the mining icon still appears on the lower left of the windows gui, but now the hashrate is incorrectly showing 0.0 kh/s. I am solo mining the same way I was in 0.9.2, with Gubiq, but the fusion wallet doesn't report my hashrate anymore.

**Comment by jyap808** [comment]
Stale issue. Not an issue.
