### ISSUE TITLE
PC clock is not synced. Really??

### ISSUE THREAD

**Issue by PSLLSP** [ubiq/fusion#45]
This is my first try of Fusion 0.10.0. I run it at Linux Mint 20.1.

First, I was not able to start file `ubiqwallet`, some library was missing. Instruction was `apt-get install libgconf2-4` but such package is not in Mint 20.1. I installed `apt-get install libgconf2-dev` and I can start `ubiqwallet`.

Second, I am welcomed with a message box, that my PC has wrong time.

```
To successfully synchronize with the Ubiq network you need to sync your computer's clock with a time sync server.

To enable a time sync server, install "ntp" via "apt-get install ntp".
```

This is not good. How is time synchronization detected?? I do not run `ntpd` but I run `chrony` that is another NTP protocol client. I am sure that my time is synchronizes with the internet and `ubiqwallet` is wrong..

```
$ chronyc sources
210 Number of sources = 7
MS Name/IP address         Stratum Poll Reach LastRx Last sample               
===============================================================================
^- pugot.canonical.com           2  10   367   478    +10ms[  +10ms] +/-   60ms
^- chilipepper.canonical.com     2  10   377   23m    -94us[-1723us] +/-   37ms
^- golem.canonical.com           2  10   375   716  +7501us[+8601us] +/-   44ms
^- alphyn.canonical.com          2  10   377   591   -444us[ -122us] +/-  111ms
^- ntp3.kashra-server.com        2  10   157   25m   +626us[ -959us] +/-   40ms
^- time.cloudflare.com           3  10   377   29m  +3098us[+1466us] +/-   16ms
^+ ntp.ms.mff.cuni.cz            2  10   377   250  +8425ns[ +268us] +/-   22ms
```

**Comment by jyap808** [comment]
Stale issue. Not an issue.
