### ISSUE TITLE
Installing Fusion with a Unique Datadir Results in Account Imports Crashing the Wallet

### ISSUE THREAD

**Issue by outragedhuman** [ubiq/fusion#6]
#### System information
``````
Version: `0.8.10`
OS & Version: Windows Server 2012 R2 (Other OS's likely affected)
Node type: `gubiq`
``````

STR:

1. Download the latest version of Fusion for Windows: https://github.com/ubiq/fusion/releases
2. During install, retain the default Fusion directory, but set the chaindata/node directory to something else (I used C:\temp\fusiontest)
3. Proceed with installation
4. Launch Fusion
5. Use accounts > import and drag a valid UBQ account file into the drop region

Expected: Fusion wallet should import the valid UBQ account file
Actual: Fusion wallet crashes with no errors.

Note: Same wallet file imports fine when a separate data directory is not chosen at install.

**Comment by ob7** [comment]
Does the wallet only crash when using the separate data directory?  Or have you observed fusion crashing even when keeping chaindata in the default directory?

**Comment by tommyms** [comment]
I have the same issue, just reinstalled the PC with Windows 10 and Fusion with data in a custom directory. When I drag the file onto the drop region the wallet just crashes (disappears).

**Comment by jyap808** [comment]
Stale issue. Not an issue.
