### ISSUE TITLE
Error in testing + 3 console errors 

### ISSUE THREAD

**Issue by bite6** [ubiq/fusion#7]
#### System information
``````
Version: `0.8.10`
OS & Version: windows
Node type: `eth
``````

Hello, 

In my Fusion wallet I have an error in the testing + 3 errors in the console. I am minning via http://ubiqpool.io and have 3.34088575 which are not transwered to the wallet yet (around 10 days).

Could you please provide me information how to fix errors in the wallet?
![ubq_wallet](https://user-images.githubusercontent.com/29356530/27012586-da1932b6-4ed2-11e7-857e-29273c8a43d3.png)

**Comment by jyap808** [comment]
in the url bar enter https://wallet.ubiqsmart.io/?reset-tabs=true
