### ISSUE TITLE
Backing up wallet

### ISSUE THREAD

**Issue by tteresi7** [ubiq/fusion#8]
Created a wallet on Fusion GUI.  However, when I use the Accounts -> Back up -> Accounts function nothing happens.

How do I backup this wallet I created in the GUI?  There is no intelligible way to do this at the moment.

**Comment by outragedhuman** [comment]
Clicking that should open up the keystore directory. Which OS are you running?

**Comment by tteresi7** [comment]
@outragedhuman Windows 10.  Clicking the button simply does nothing.

**Comment by iquidus** [comment]
Your OS's filebrowser opens %AppData%/Roaming/Ubiq where you can see a keystore directory. that keystore dir contains a .json file for each of your addresses.

**Comment by tteresi7** [comment]
@iquidus there is no ubiq folder in the roaming folder.  In the fusion folder there only exists two jsons window-state and clientBinaries

**Comment by jyap808** [comment]
please sign up to slack.ubiqsmart.com if you need further assistance

**Comment by tteresi7** [comment]
@jyap808 Do you have a pull request which fixes this problem, or are you simply closing the subject because you feel like it?  There is clearly a function included in the GUI that is not working properly and you choose not to address it?  Fixing the bug is not an item to be discussed in slack for "further assistance" it is an item to be listed under TO DO.

**Comment by jyap808** [comment]
the community slack is for real-time assistance.

In Fusion if you go Accounts > Backup it will open the keystore folder. Backup your keystore files (file names start with UTC).

**Comment by tteresi7** [comment]
@jyap808 I'm not looking for real time assistance, I'm addressing a bug in your GUI.  Accounts > Backup > Accounts does not do anything.  Nothing pops up, nothing refreshes, nothing gets saved.  This is clearly a bug.

**Comment by jyap808** [comment]
I see. I'll re-open it then. We get a few support requests through here if you look at the closed Issues. My bad.

**Comment by tribalpixel** [comment]
same problem for me

**Comment by szikra** [comment]
I have the same issue. 
During install I changed the application install location, this might cause the bug to appear.

I have found a file in
install location\keystore\UTC--*date*time*--*address*
which starts with
{"address":

Is this the only file I need or is there something else?

**Comment by notracking** [comment]
Here is what happens:

If you choose to install (under Windows 7 at least) and You set a non-standard DATA directory the keyfile will be stored there and **not** in your default c:\users\USERNAME\appdata\roaming...

Though the backup option will still lead you to the appdata\roaming dir the keyfile directory is there, but that one is empty. This is a nasty bug anmd will lead to a lot of people losing access to their wallets.

**Comment by notracking** [comment]
to find the correct keyfile location in Windows always check the Target in the Fusion shortcut, that one will point to the correct location. The actual keyfile is stored in the path given to the application parameter **--node-datadir**

**Comment by notracking** [comment]
Still the backup wallet option in de application is very misleading, because in some situations it will point to a empty keyfile directory. But that is just my 2c.

**Comment by mak1986** [comment]
@notracking Thank you for pointing this out :)
