### ISSUE TITLE
How do I get my seed/private key?

### ISSUE THREAD

**Issue by cryptoczars** [ubiq/fusion#9]
I created a wallet but never was given a seed or private keys. I am on a Mac.

#### System information
``````
Version: '0.0.0'
OS & Version: 10.10.5 osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by jyap808** [comment]
Load up the keystore in Pyrus (pyrus.ubiqsmart.com). It will show you the private key.. That's the easiest way.

**Comment by cryptoczars** [comment]
but i dont have the keystore. I only have the fusion app wallet app. There was never a keystore or seed given

**Comment by jyap808** [comment]
In Fusion if you go Accounts > Backup it will open the keystore folder. Backup your keystore files (file names start with UTC).

**Comment by cryptoczars** [comment]
ahh ok got it thank you
